"""
================================================================================
Phase-Curve Plot
================================================================================

Reads PhaseCurve_*.mat files generated by compute_phase_curve.m and produces
dual-y-axis waveform/amplitude-vs-phase figures.

State (running / non_running / all_epochs) in those .mats is produced by compute_phase_curve.m
using the same strict per-sample velocity rules as compute_state_spectrogram.m (all samples
> 2 cm/s for running, all < 0.1 cm/s for rest; no mean-velocity fallback; no re-classification
in this plotting script).

  Left  y-axis : Theta waveform from bandpass-filtered raw signal (phase-triggered average,
                 5–9 Hz); fallback to theta_curve × sin(phase) if waveform field missing
  Right y-axis : Low γ amplitude (30–60 Hz); LFP purple + amber gold, Fiber blue + green

X-axis shows two full theta cycles (0–720°) when independent 2-cycle data is
available; falls back to one cycle (0–360°) otherwise.

Input:
  Process/phase_curve/{condition}/{animal}/PhaseCurve_{SignalType}_{state}.mat

Output:
  Figures/phase_curve/{condition}/{animal}/
    {animal}_{SignalType}_{state}_phase_curve.png / .pdf / .svg

Usage:
    python plot_phase_curve.py
================================================================================
"""

import os
import re
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from scipy.io import loadmat
from pathlib import Path
from datetime import datetime
import warnings

warnings.filterwarnings('ignore', category=UserWarning)


# ==============================================================================
#  CONFIGURATION
# ==============================================================================

SCRIPT_DIR  = Path(__file__).parent.resolve()
PROJECT_DIR = SCRIPT_DIR.parent
PROCESS_DIR = PROJECT_DIR / "Process" / "phase_curve"

FIGURES_DIR = PROJECT_DIR / "Figures" / "phase_curve"

FIGURE_DPI    = 300
FIGURE_FORMAT = ['png', 'pdf', 'svg']

STATES = ['running', 'non_running', 'all_epochs']
STATE_LABELS = {
    'running':     'Running',
    'non_running': 'Rest',
    'all_epochs':  'All Epochs',
}

# Frequency bands (must match compute_phase_curve.m)
THETA_BAND = [5,  9]
GAMMA_BAND = [30, 60]

# ------------------------------------------------------------------------------
# Colour scheme — per-signal colour families
# ------------------------------------------------------------------------------
# LFP family:   purple (theta) + warm gold (gamma)
# Fiber family:  blue (theta)  + emerald green (gamma)
COLOR_THETA_LFP   = (0.50, 0.15, 0.55)    # deep purple
COLOR_THETA_FIBER = (0.15, 0.30, 0.70)    # true blue
ALPHA_THETA   = 1.0
LW_THETA      = 1.8

COLOR_GAMMA_LFP   = (0.80, 0.52, 0.12)   # warm gold / amber
COLOR_GAMMA_FIBER = (0.12, 0.62, 0.38)   # emerald / bright green (matches spectrogram)

ALPHA_GAMMA = 1.0
LW_GAMMA    = 1.8

# Cycle boundary line
COLOR_BOUNDARY = (0.5, 0.5, 0.5)

# Signal labels (corner annotation, consistent with other scripts)
SIGNAL_LABELS = {
    'LFP':    'LFP',
    'Fiber1': 'Pyr',
    'Fiber2': 'Pyr2',
}
# PV voltage-imaging animals: use 'PV+' instead of 'Pyr'
PV_CONDITION = 'PV_Animals'
PV_SIGNAL_LABELS = {
    'Fiber1': 'PV+',
    'Fiber2': 'PV+',
}


def get_signal_label(signal_type, condition):
    """Return display label for signal (Pyr vs PV by condition)."""
    if condition == PV_CONDITION and signal_type in PV_SIGNAL_LABELS:
        return PV_SIGNAL_LABELS[signal_type]
    return SIGNAL_LABELS.get(signal_type, signal_type)


def _decode_mat_char(val):
    """Decode MATLAB strings from loadmat.

    scipy may return (a) a numpy str scalar, (b) a 1×N ``char`` vector as ``<U1``
    per column — taking only ``[0]`` would yield a single letter and break
    ``signal_type == 'LFP'`` / corner labels. Join multi-element unicode/byte arrays.
    """
    if val is None:
        return ''
    if isinstance(val, bytes):
        return val.decode('utf-8', errors='replace').strip()
    if isinstance(val, np.ndarray):
        if val.size == 0:
            return ''
        if val.dtype == object:
            return _decode_mat_char(np.asarray(val.item()))
        flat = np.ravel(val)
        if flat.size == 1:
            x = flat[0]
            if isinstance(x, bytes):
                return x.decode('utf-8', errors='replace').strip()
            return str(x).strip()
        # Per-character MATLAB char row (e.g. 'Fiber1' as 6× <U1)
        if flat.dtype.kind in ('U', 'S'):
            out = []
            for t in flat:
                if isinstance(t, bytes):
                    out.append(t.decode('utf-8', errors='replace'))
                else:
                    out.append(str(t))
            return ''.join(out).strip()
        # uint16 UTF-16 (some MATLAB char saves)
        if flat.dtype == np.uint16 and flat.size > 1:
            try:
                return flat.tobytes().decode('utf-16-le', errors='replace').replace(
                    '\x00', ''
                ).strip()
            except Exception:
                pass
        x = flat[0]
        if isinstance(x, bytes):
            return x.decode('utf-8', errors='replace').strip()
        return str(x).strip()
    return str(val).strip()


def _lfp_wavelet_is_z_scored(lfp_ephys_field):
    s = _decode_mat_char(lfp_ephys_field).lower()
    if not s:
        return False
    if s in ('lfp_z_hp', 'lfp_z'):
        return True
    if s.startswith('lfp_z_'):
        return True
    return False


def lfp_phase_curve_y_axis_unit(lfp_ephys_field):
    """Left (LFP θ waveform) and right (LFP γ band) Y-axis unit."""
    return 'a.u.' if _lfp_wavelet_is_z_scored(lfp_ephys_field) else 'mV'


# ==============================================================================
#  HELPER FUNCTIONS
# ==============================================================================

def load_phase_curve(mat_path):
    """Load a PhaseCurve_*.mat file into a dict."""
    raw = loadmat(str(mat_path), squeeze_me=True, struct_as_record=False)
    d = {}
    for key in ['animal_name', 'condition', 'signal_type', 'state',
                'theta_band', 'gamma_band', 'freq_vector',
                'phase_bins_deg', 'two_cycle_deg',
                'theta_curve_1cyc', 'gamma_curve_1cyc',
                'theta_curve_2cyc', 'gamma_curve_2cyc',
                'theta_waveform_1cyc', 'theta_waveform_2cyc',
                'theta_waveform_ci95_1cyc', 'theta_waveform_ci95_2cyc',
                'gamma_raw_1cyc', 'gamma_raw_2cyc',
                'gamma_ci95_1cyc', 'gamma_ci95_2cyc',
                'n_epochs', 'mean_velocity', 'lfp_ephys_field',
                'has_independent_2cyc']:
        if key in raw:
            val = raw[key]
            if isinstance(val, np.ndarray) and val.ndim == 0:
                val = val.item()
            d[key] = val
    for sk in ('lfp_ephys_field', 'signal_type', 'state', 'animal_name', 'condition'):
        if sk in d:
            d[sk] = _decode_mat_char(d[sk])
    return d


def _format_yaxis(ax, curve, color, ylabel, symmetric=False, side='left', ylim=None):
    """Style one y-axis: ticks, label, and the relevant spine color only.

    side='left'  → color the left spine (for the primary axis)
    side='right' → color the right spine (for the twinx axis)
    ylim: optional (lo, hi) to force axis range (for run/rest scale unification)
    """
    ax.set_ylabel(ylabel, color=color, fontsize=10)
    ax.tick_params(axis='y', colors=color, labelsize=9)
    ax.spines[side].set_color(color)

    if ylim is not None:
        lo, hi = ylim
    else:
        lo, hi = np.nanmin(curve), np.nanmax(curve)

    if symmetric:
        bound = max(abs(lo), abs(hi))
        pad = bound * 0.15
        ax.set_ylim(-bound - pad, bound + pad)
        ticks = np.linspace(-bound, bound, 5)
    else:
        pad = (hi - lo) * 0.12 if hi > lo else 0.01
        ax.set_ylim(lo - pad, hi + pad)
        ticks = np.linspace(lo, hi, 5)

    ax.set_yticks(ticks)
    mag = max(abs(lo), abs(hi))
    if mag > 0:
        exp = int(np.floor(np.log10(mag)))
    else:
        exp = 0
    scale = 10 ** exp
    ax.set_yticklabels([f'{t/scale:.1f}' for t in ticks], fontsize=8)
    return exp


def parse_gamma_suffix_from_mat_stem(stem):
    """Extract gamma band suffix from PhaseCurve filename, e.g. PhaseCurve_Fiber1_running_30-50Hz -> '30-50Hz'."""
    m = re.search(r'_(\d+-\d+Hz)$', stem)
    return m.group(1) if m else None


def _use_2cyc(data):
    """True when genuine independent 2-cycle data exists."""
    flag = data.get('has_independent_2cyc', False)
    if isinstance(flag, np.ndarray):
        flag = bool(flag.flat[0])
    return bool(flag) and 'theta_waveform_2cyc' in data


def _compute_axis_ranges_from_data(data):
    """Compute (theta_lo, theta_hi) and (gamma_lo, gamma_hi), including CI."""
    if _use_2cyc(data):
        theta = np.asarray(data['theta_waveform_2cyc']).flatten()
        theta_ci = np.asarray(data.get('theta_waveform_ci95_2cyc', np.zeros_like(theta))).flatten()
        gamma = np.asarray(data.get('gamma_raw_2cyc', data['gamma_curve_2cyc'])).flatten()
        gamma_ci = np.asarray(data.get('gamma_ci95_2cyc', np.zeros_like(gamma))).flatten()
    else:
        theta = np.asarray(data.get('theta_waveform_1cyc', data['theta_curve_1cyc'])).flatten()
        theta_ci = np.asarray(data.get('theta_waveform_ci95_1cyc', np.zeros_like(theta))).flatten()
        gamma = np.asarray(data.get('gamma_raw_1cyc', data['gamma_curve_1cyc'])).flatten()
        gamma_ci = np.asarray(data.get('gamma_ci95_1cyc', np.zeros_like(gamma))).flatten()
    theta_lo = np.nanmin(theta - theta_ci)
    theta_hi = np.nanmax(theta + theta_ci)
    gamma_lo = np.nanmin(gamma - gamma_ci)
    gamma_hi = np.nanmax(gamma + gamma_ci)
    return (theta_lo, theta_hi), (gamma_lo, gamma_hi)


def create_phase_curve_figure(data, output_dir, ylim_left=None, ylim_right=None):
    """
    Create and save a dual-y-axis phase-curve figure for a single
    (signal_type, state) combination.
    """
    signal_type = _decode_mat_char(data.get('signal_type', ''))
    state       = _decode_mat_char(data.get('state', ''))
    animal_name = _decode_mat_char(data.get('animal_name', ''))

    two_cycle = _use_2cyc(data)

    phase_bins_deg = np.asarray(data['phase_bins_deg']).flatten()
    phase_deg_1cyc = phase_bins_deg + 180.0  # shift -180:180 → 0:360

    if two_cycle:
        two_cycle_deg  = np.asarray(data['two_cycle_deg']).flatten()
        theta_waveform = np.asarray(data['theta_waveform_2cyc']).flatten()
        theta_ci       = np.asarray(data.get('theta_waveform_ci95_2cyc',
                                             np.zeros_like(theta_waveform))).flatten()
        gamma_curve    = np.asarray(data.get('gamma_raw_2cyc',
                                             data['gamma_curve_2cyc'])).flatten()
        gamma_ci       = np.asarray(data.get('gamma_ci95_2cyc',
                                             np.zeros_like(gamma_curve))).flatten()
        phase_deg      = two_cycle_deg
        phase_max      = 720.0
        xticks         = [0, 90, 180, 270, 360, 450, 540, 630, 720]
    else:
        gamma_curve = np.asarray(data['gamma_curve_1cyc']).flatten()
        if 'theta_waveform_1cyc' in data:
            theta_waveform = np.asarray(data['theta_waveform_1cyc']).flatten()
        else:
            theta_curve_1cyc = np.asarray(data['theta_curve_1cyc']).flatten()
            theta_waveform   = theta_curve_1cyc * np.sin(np.deg2rad(phase_deg_1cyc))
            print('    [WARN] theta_waveform_1cyc not found – rerun compute_phase_curve.m')
        theta_ci = np.asarray(data.get('theta_waveform_ci95_1cyc',
                                       np.zeros_like(theta_waveform))).flatten()
        if 'gamma_raw_1cyc' in data:
            gamma_curve = np.asarray(data['gamma_raw_1cyc']).flatten()
        gamma_ci = np.asarray(data.get('gamma_ci95_1cyc',
                                       np.zeros_like(gamma_curve))).flatten()
        phase_deg = phase_deg_1cyc
        phase_max = 360.0
        xticks    = [0, 90, 180, 270, 360]

    n_epochs      = int(data.get('n_epochs', 0))
    state_label   = STATE_LABELS.get(state, state)
    condition     = str(data.get('condition', ''))
    corner_label  = get_signal_label(signal_type, condition)

    theta_color = COLOR_THETA_LFP if signal_type == 'LFP' else COLOR_THETA_FIBER
    gamma_color = COLOR_GAMMA_LFP if signal_type == 'LFP' else COLOR_GAMMA_FIBER

    if signal_type == 'LFP':
        unit = lfp_phase_curve_y_axis_unit(data.get('lfp_ephys_field', ''))
    else:
        unit = '%'

    # ------------------------------------------------------------------
    # Close the curve at the end: repeat first bin value at phase_max
    # ------------------------------------------------------------------
    def _close(x, y):
        return np.concatenate([x, [phase_max]]), np.concatenate([y, [y[0]]])

    deg_th, theta_waveform = _close(phase_deg, theta_waveform)
    _,      theta_ci       = _close(phase_deg, theta_ci)
    deg_gm, gamma_curve    = _close(phase_deg, gamma_curve)
    _,      gamma_ci       = _close(phase_deg, gamma_ci)

    # ---------- Figure ----------
    fig = plt.figure(figsize=(5.0, 3.8))
    ax_left  = fig.add_axes([0.14, 0.15, 0.60, 0.74])
    ax_right = ax_left.twinx()

    # Reposition right spine via ax_right (already done by twinx)
    ax_right.spines['right'].set_visible(True)

    # Plot theta waveform (left) — signed oscillation + 95% CI shading
    ax_left.plot(deg_th, theta_waveform,
                 color=theta_color, linewidth=LW_THETA, alpha=ALPHA_THETA,
                 zorder=3, label=f'Theta ({THETA_BAND[0]}–{THETA_BAND[1]} Hz)')
    if np.any(theta_ci > 0):
        ax_left.fill_between(deg_th,
                             theta_waveform - theta_ci,
                             theta_waveform + theta_ci,
                             color=theta_color, alpha=0.18, linewidth=0, zorder=2)
    ax_left.axhline(0, color=theta_color, linewidth=0.5, linestyle=':', alpha=0.4, zorder=1)

    # Gamma band from .mat (PV fiber uses 40-60 Hz)
    gamma_band = np.asarray(data.get('gamma_band', GAMMA_BAND)).flatten()
    if len(gamma_band) < 2:
        gamma_band = np.array(GAMMA_BAND)

    # Plot gamma (right) + 95% CI shading
    ax_right.plot(deg_gm, gamma_curve,
                  color=gamma_color, linewidth=LW_GAMMA, alpha=ALPHA_GAMMA,
                  zorder=2, label=f'Low Gamma ({int(gamma_band[0])}–{int(gamma_band[1])} Hz)')
    if np.any(gamma_ci > 0):
        ax_right.fill_between(deg_gm,
                              gamma_curve - gamma_ci,
                              gamma_curve + gamma_ci,
                              color=gamma_color, alpha=0.18, linewidth=0, zorder=1)

    # Cycle boundary line (2-cycle mode only)
    if two_cycle:
        ax_left.axvline(360, color='#999999', linewidth=0.7, linestyle='--', alpha=0.5, zorder=0)

    # X-axis
    ax_left.set_xlim(0, phase_max)
    ax_left.set_xticks(xticks)
    ax_left.set_xlabel('LFP Theta Phase (deg.)', fontsize=10)
    ax_left.tick_params(axis='x', labelsize=9)

    # Y-axis formatting
    # Expand curves by CI so Y limits always contain the shading (used when ylim not provided)
    theta_for_ylim = np.concatenate([theta_waveform + theta_ci,
                                     theta_waveform - theta_ci])
    gamma_for_ylim = np.concatenate([gamma_curve + gamma_ci,
                                     gamma_curve - gamma_ci])

    left_ylabel = f'θ waveform ({unit})'
    exp_theta = _format_yaxis(ax_left,  theta_for_ylim, theta_color,
                             left_ylabel, symmetric=True, side='left',
                             ylim=ylim_left)
    right_ylabel = f'Low γ amplitude ({unit})'
    exp_gamma = _format_yaxis(ax_right, gamma_for_ylim, gamma_color,
                             right_ylabel, side='right',
                             ylim=ylim_right)

    # Hide ax_right's left spine so it never overlaps / recolors the left axis
    ax_right.spines['left'].set_visible(False)

    # Exponent annotations – anchor exactly at top of each Y-axis spine, zero horizontal offset
    # Left : xy=(0,1)=spine top, xytext=(0,4) → text right edge on spine, ha='right'
    # Right: xy=(1,1)=spine top, xytext=(0,4) → text left edge on spine, ha='left'
    if exp_theta != 0:
        ax_left.annotate(
            f'×10$^{{{exp_theta}}}$',
            xy=(0, 1), xycoords='axes fraction',
            xytext=(0, 4), textcoords='offset points',
            fontsize=8, color=theta_color, ha='right', va='bottom',
        )
    if exp_gamma != 0:
        ax_right.annotate(
            f'×10$^{{{exp_gamma}}}$',
            xy=(1, 1), xycoords='axes fraction',
            xytext=(0, 4), textcoords='offset points',
            fontsize=8, color=gamma_color, ha='left', va='bottom',
        )

    # Spines
    ax_left.spines['top'].set_visible(False)
    ax_right.spines['top'].set_visible(False)
    ax_left.spines['bottom'].set_linewidth(1.0)
    ax_left.spines['left'].set_linewidth(1.0)
    ax_right.spines['right'].set_linewidth(1.0)

    # Corner annotation (signal type label) – placed ABOVE the exponent row
    ax_left.text(0.02, 1.11, corner_label, transform=ax_left.transAxes,
                 fontsize=13, fontweight='bold', ha='left', va='bottom')

    # State label (top right) – same row as signal label
    ax_left.text(0.98, 1.11, state_label, transform=ax_left.transAxes,
                 fontsize=9, ha='right', va='bottom', color='#444444')

    # Epoch count (bottom right, inside plot)
    ax_left.text(0.97, 0.04, f'n = {n_epochs} epochs',
                 transform=ax_left.transAxes,
                 fontsize=8, ha='right', va='bottom', color='#666666')

    # Save
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    base_name = f'{animal_name}_{signal_type}_{state}_phase_curve'

    for fmt in FIGURE_FORMAT:
        save_path = output_dir / f'{base_name}.{fmt}'
        kwargs = dict(dpi=FIGURE_DPI, bbox_inches='tight')
        if fmt == 'svg':
            fig.savefig(save_path, facecolor='none', edgecolor='none',
                        transparent=True, **kwargs)
        else:
            fig.savefig(save_path, facecolor='white', edgecolor='none', **kwargs)
        print(f'    Saved: {save_path.name}')

    plt.close(fig)


def _parse_mat_file_key(mat_path):
    """Parse (signal_type, state) from PhaseCurve filename stem.
    e.g. PhaseCurve_Fiber1_non_running -> ('Fiber1', 'non_running')
    """
    stem = mat_path.stem
    rest = stem.replace('PhaseCurve_', '')
    gamma_suffix = parse_gamma_suffix_from_mat_stem(stem)
    if gamma_suffix:
        rest = rest[:-len(gamma_suffix) - 1]
    parts = rest.split('_')
    if len(parts) >= 2:
        signal_type = parts[0]
        state = '_'.join(parts[1:])
        return signal_type, state
    return None, None


def process_animal(animal_path):
    """Process all PhaseCurve_*.mat files for one animal.
    Unifies left/right y-axis scales across running and rest within each signal_type group.
    """
    animal_name    = animal_path.name
    condition_name = animal_path.parent.name

    print(f'\n{"="*60}')
    print(f'Processing animal : {animal_name}')
    print(f'Condition         : {condition_name}')
    print(f'{"="*60}')

    output_base = FIGURES_DIR / condition_name / animal_name

    mat_files = sorted(animal_path.glob('PhaseCurve_*.mat'))
    if not mat_files:
        print(f'  No PhaseCurve_*.mat files found in {animal_path}')
        return

    RUN_REST = {'running', 'non_running'}
    groups = {}  # signal_type -> list of (mat_path, state)
    for mat_path in mat_files:
        signal_type, state = _parse_mat_file_key(mat_path)
        if signal_type is None:
            continue
        if signal_type not in groups:
            groups[signal_type] = []
        groups[signal_type].append((mat_path, state))

    for signal_type, items in groups.items():
        run_rest_items = [(p, s) for p, s in items if s in RUN_REST]
        ylim_left, ylim_right = None, None

        if len(run_rest_items) >= 2:
            theta_lo_list, theta_hi_list = [], []
            gamma_lo_list, gamma_hi_list = [], []
            for mat_path, _ in run_rest_items:
                try:
                    data = load_phase_curve(mat_path)
                    (tlo, thi), (glo, ghi) = _compute_axis_ranges_from_data(data)
                    theta_lo_list.append(tlo)
                    theta_hi_list.append(thi)
                    gamma_lo_list.append(glo)
                    gamma_hi_list.append(ghi)
                except Exception:
                    pass
            if theta_lo_list and gamma_lo_list:
                theta_lo, theta_hi = min(theta_lo_list), max(theta_hi_list)
                gamma_lo, gamma_hi = min(gamma_lo_list), max(gamma_hi_list)
                ylim_left = (theta_lo, theta_hi)
                ylim_right = (gamma_lo, gamma_hi)

        for mat_path, state in items:
            print(f'\n  [{mat_path.stem}]')
            try:
                data = load_phase_curve(mat_path)
            except Exception as e:
                print(f'    Error loading: {e}')
                continue

            out_dir = output_base / signal_type / state
            use_ylim_left = ylim_left if state in RUN_REST and ylim_left else None
            use_ylim_right = ylim_right if state in RUN_REST and ylim_right else None

            try:
                create_phase_curve_figure(data, out_dir,
                                          ylim_left=use_ylim_left, ylim_right=use_ylim_right)
            except Exception as e:
                print(f'    Error creating figure: {e}')

    # Write manifest
    _write_phase_curve_manifest(animal_path, mat_files, animal_name, condition_name, output_base)


def _write_phase_curve_manifest(animal_path, mat_files, animal_name, condition_name, output_base):
    """Write manifest.txt with source files, analysis parameters, and timestamps."""

    # --- Read parameters from the first available .mat ---
    theta_band, gamma_band = '?', '?'
    lfp_field, n_phase_bins = '?', '?'
    freq_range_str, n_freq_bins = '?', '?'
    has_2cyc = '?'
    state_info = {}  # (signal, state) -> n_epochs

    for mf in mat_files:
        try:
            raw = loadmat(str(mf), squeeze_me=True)
            sig = _decode_mat_char(raw.get('signal_type', '?'))
            st = _decode_mat_char(raw.get('state', '?'))
            ne = raw.get('n_epochs', '?')
            state_info[(sig, st)] = ne

            if theta_band == '?':
                tb = raw.get('theta_band')
                if tb is not None:
                    theta_band = np.asarray(tb).flatten()
                gb = raw.get('gamma_band')
                if gb is not None:
                    gamma_band = np.asarray(gb).flatten()
                lf = raw.get('lfp_ephys_field')
                if lf is not None:
                    lfp_field = _decode_mat_char(lf) or '?'
                pb = raw.get('phase_bins_deg')
                if pb is not None:
                    n_phase_bins = str(np.asarray(pb).flatten().size)
                fv = raw.get('freq_vector')
                if fv is not None:
                    fv = np.asarray(fv).flatten()
                    freq_range_str = f"{fv[0]:.1f} – {fv[-1]:.1f} Hz"
                    n_freq_bins = str(fv.size)
                h2 = raw.get('has_independent_2cyc')
                if h2 is not None:
                    has_2cyc = 'Yes' if int(h2) else 'No'
        except Exception:
            pass

    # --- Try reading upstream Results for extra metadata ---
    spec_animal_dir = animal_path.parent.parent / "phase_aligned_spectrogram" / condition_name / animal_name
    sampling_rate, phase_method, phase_source, wavelet_cycles = '?', '?', '?', '?'
    cycles_per_epoch = '?'
    run_thresh, nonrun_thresh = '?', '?'
    trial_dirs = []

    if spec_animal_dir.is_dir():
        trial_dirs = sorted([
            d.name for d in spec_animal_dir.iterdir()
            if d.is_dir() and d.name != 'run_nonrun'
        ])
        for td_name in trial_dirs[:1]:
            results_glob = list((spec_animal_dir / td_name).rglob(
                'PhaseAlignedSpectrogram_Results_*.mat'))
            if not results_glob:
                continue
            try:
                import mat73 as _m73
                res = _m73.loadmat(str(results_glob[0]))
                meta = (res.get('results') or res).get('metadata', {})
                sampling_rate = meta.get('sampling_rate', '?')
                phase_method = meta.get('phase_method', '?')
                phase_source = meta.get('phase_source', '?')
                wavelet_cycles = meta.get('wavelet_cycles', '?')
                cycles_per_epoch = meta.get('cycles_per_epoch', '?')
            except Exception:
                pass
        for rn_mat in spec_animal_dir.rglob('run_nonrun/**/PhaseAlignedSpectrogram_*.mat'):
            try:
                md = loadmat(str(rn_mat), squeeze_me=True)
                if 'running_threshold' in md:
                    run_thresh = md['running_threshold']
                if 'non_running_threshold' in md:
                    nonrun_thresh = md['non_running_threshold']
                if lfp_field == '?' and 'lfp_ephys_field' in md:
                    lfp_field = _decode_mat_char(md['lfp_ephys_field']) or '?'
                break
            except Exception:
                pass

    lines = [
        "Phase Curve Figures — Generation Manifest",
        "==========================================",
        f"Animal:     {animal_name}",
        f"Condition:  {condition_name}",
        f"Generated:  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        f"Source data: Process/phase_curve/{condition_name}/{animal_name}/",
        "",
        f"Input .mat files ({len(mat_files)}):",
    ]
    for mf in mat_files:
        lines.append(f"  - {mf.name}")

    if trial_dirs:
        lines += [
            "",
            f"Upstream spectrogram trials ({len(trial_dirs)}):",
        ]
        for t in trial_dirs:
            lines.append(f"  - {t}")

    lines += [
        "",
        "=== Analysis Parameters ===",
        f"LFP source field:          {lfp_field}",
        f"Sampling rate:             {sampling_rate} Hz",
        "",
        "Phase extraction:",
        f"  Low-frequency (theta) band: {theta_band} Hz",
        f"  Method:                  {phase_method}",
        f"  Phase source:            {phase_source}",
        "",
        "Wavelet spectrogram:",
        f"  Frequency range:         {freq_range_str}",
        f"  Number of freq bins:     {n_freq_bins}",
        f"  Morlet wavelet cycles:   {wavelet_cycles}",
        "",
        "Phase curve bands:",
        f"  Theta (waveform) band:   {theta_band} Hz",
        f"  Gamma (magnitude) band:  {gamma_band} Hz",
        "",
        "Epoch & phase binning:",
        f"  Cycles per epoch:        {cycles_per_epoch}",
        f"  Number of phase bins:    {n_phase_bins}",
        f"  Independent 2-cycle:     {has_2cyc}",
        "",
        "Velocity classification (strict per-sample):",
        f"  Running threshold:       > {run_thresh} cm/s (ALL samples in epoch)",
        f"  Rest threshold:          < {nonrun_thresh} cm/s (ALL samples in epoch)",
        f"  Intermediate epochs excluded from running/rest averages",
        "",
        "=== Epoch Counts Per State ===",
    ]
    for (sig, st), ne in sorted(state_info.items()):
        lines.append(f"  {st:15s} / {sig:8s}: {ne} epochs")

    lines += [
        "",
        f"Script: Code/plot_phase_curve.py",
    ]

    content = "\n".join(lines) + "\n"
    output_base.mkdir(parents=True, exist_ok=True)
    manifest_path = output_base / "manifest.txt"
    manifest_path.write_text(content, encoding="utf-8")
    print(f"  Manifest written: {manifest_path}")


def find_all_animals(base_dir):
    """Find all animal-level folders under Process/phase_curve/."""
    base_dir = Path(base_dir)
    animals  = []
    for condition in base_dir.iterdir():
        if not condition.is_dir():
            continue
        for animal in condition.iterdir():
            if animal.is_dir():
                animals.append(animal)
    return sorted(animals)


# ==============================================================================
#  MAIN
# ==============================================================================

def main():
    print('=' * 70)
    print('Phase-Curve Plotting Script')
    print('=' * 70)
    print(f'Theta band : {THETA_BAND[0]}–{THETA_BAND[1]} Hz')
    print(f'Gamma band : {GAMMA_BAND[0]}–{GAMMA_BAND[1]} Hz')

    if not PROCESS_DIR.exists():
        print(f'\nError: Process directory not found: {PROCESS_DIR}')
        print('Run compute_phase_curve.m first.')
        return

    animals = find_all_animals(PROCESS_DIR)
    if not animals:
        print(f'\nNo animal data found in: {PROCESS_DIR}')
        return

    print(f'\nFound {len(animals)} animal(s):')
    for a in animals:
        print(f'  - {a.parent.name}/{a.name}')

    for animal_path in animals:
        process_animal(animal_path)

    print('\n' + '=' * 70)
    print('Processing complete!')
    print(f'Figures saved to: {FIGURES_DIR}')
    print('=' * 70)


if __name__ == '__main__':
    main()
